const cities = {
    'All' : false,
    'City ': false,
    'Frederiksbjerg': false,
    'Vesterbro': false,
    'Trøjborg': false,
    "Aarhus Ø (Bynære havnearealer) + Havnen": false,
    "Holme-Højbjerg-Skåde": false,
    'Viby': false,
    'Hasle': false,
    'Christiansbjerg': false,
    "Vejlby-Risskov": false,
    'Åby': false,
    "Tranbjerg": false,
    "Hasselager-Kolt": false,
    "Stavtrup-Ormslev": false,
    "Brabrand-Gjellerup": false,
    "Tilst-Brabrand Nord": false,
    "Skejby-Lisbjerg": false,
    "Lystrup-Elsted-Elev": false,
    "Skæring-Egå": false,
    "Beder-Malling": false,
    'Mårslet': false,
    'Solbjerg': false,
    "Harlev-Framlev": false,
    "Sabro-Borum": false,
    "Trige-Spørring": false,
    "Hårup-Mejlby": false,
    'Hjortshøj': false,
    'Løgten-Skødstrup': false,
}

export {cities}